### ISSUE TITLE
Links disappear

### ISSUE THREAD

**Issue by gilados** [sboulema/StackTraceExplorer#12]
Hi,
In the last release, I can now drag a file into the window but once I click on one of the links - they all disappear - see below:

https://screenpresso.com/=mLLAc

Thanks,
Gilad.

**Comment by sboulema** [comment]
Thanks for reporting this! It is probably related to the blue theme...

**Comment by sboulema** [comment]
Grab the new release! https://github.com/sboulema/StackTraceExplorer/releases/tag/v1.11.35

**Comment by gilados** [comment]
Issue is now fix - Thanks!
