### ISSUE TITLE
Going to a method or type takes 2 seconds

### ISSUE THREAD

**Issue by noam-honig** [sboulema/StackTraceExplorer#6]
First let me say that I love this stack explorer - specifically the colors.

I have a solution with not a lot of code - 6 projects, and when I click in the stack on a method or class it takes around 2 seconds.
Clicking on a file runs fast.

I understand that clicking on a method is more complex - but still 2 seconds seems like much.

I compare it to another stack explorer (https://github.com/terrajobst/stack-trace-explorer) that does that faster :)

Is there anything that can be done?

**Comment by sboulema** [comment]
Thanks for reporting and thanks for some good inspiration.

Please try the new build: https://github.com/sboulema/StackTraceExplorer/releases/tag/v1.9.25

**Comment by noam-honig** [comment]
Tested it - looks great
