### ISSUE TITLE
Click on class to navigate to class

### ISSUE THREAD

**Issue by noam-honig** [sboulema/StackTraceExplorer#7]
I have this call stack:
```
   at Northwind.Orders.ShowOrders.Details.Run() in C:\demos\Dotnet\Northwind.Orders\ShowOrders.cs:line 168
```

When I hover over it with my mouse - I get a link for the "Run" method and a link for "Northwind.Orders.ShowOrders"

When I click on the Run method - it goes to it.
When I click on the "Northwind.Orders.ShowOrders" I expected it to go to the class, but it also goes to the Run method.

Northwind and Orders are namespaces, ShowOrders is a class, and Details is an inner class.

Ideally  - It'll be great if:
1. When I click on Run - it'll go to the run method.
2. When I click on Details - it'll go to the Details inner class
3. When I click on ShowOrders it'll go to the Show Orders class

**Comment by sboulema** [comment]
Added clicking on namespaces and classes in the new release!

Please try it out and let me know if everything is ok: https://github.com/sboulema/StackTraceExplorer/releases/tag/v1.10.28

**Comment by sboulema** [comment]
Yeah had the same issues locally, will look into them

**Comment by noam-honig** [comment]
Sorry, still doesn't work well.

Using the same stack:
at Northwind.Orders.ShowOrders.Details.Run() 

1. Click on Run, used to work and now doesn't.
2. Clicking on Details should go to the inner class "Details" of the class "Orders" it doesn't go there.
3. Clicking on ShowOrders should go to the ShowOrders class - instead it goes to the line describing the namespace "Northwind.SHared.Theme.Colors"
![image](https://user-images.githubusercontent.com/16635859/40537655-2473925a-6018-11e8-8fad-b71969eb6cb2.png)
4. Clicking on Orders  goes to the Orders namespace, and Northwind namespace  - I don't think there is any use to going to a namespace - because it doesn't get you to a single file, so I think you can remove that feature :)

Hope this helps.

**Comment by sboulema** [comment]
This is going to sound repetitive...
Please try the new release: https://github.com/sboulema/StackTraceExplorer/releases/tag/v1.10.30

Background:
There is a regular expression trying to parse these code member definitions and it is tricky to get it right.

**Comment by noam-honig** [comment]
Sorry, still no go - here's a screen shot:
![image](https://user-images.githubusercontent.com/16635859/40582977-001b10c4-618d-11e8-8105-1801d26f3f18.png)

1. The underline is under the entire namespace and classes.
2. Clicking on the classes or the methods doesn't work for most cases.
    1. For the first line clicking on the class (run) always goes to that method (run), I expected that I'll be able to click on the Details inner class and go to it, and on the ShowOrders class and be able to go to it.
     2. Clicking on any other line just doesn't go there.
3. Lines 2 and 4 are not highlighted.

I get the pain of parsing it - I'm not a fan of Regular expressions, 
Whenever I have such code where I change one thing, something other breaks - that's when I use small unit tests - you've probably done that.

**Comment by sboulema** [comment]
Please try: https://github.com/sboulema/StackTraceExplorer/releases/tag/v1.10.31

Added unit tests to validate the Regular expression
Updated the Regular expression

**Comment by noam-honig** [comment]
Looks good - let me know when you release it to Visual Studio Market place, so I'll start referencing it.

**Comment by sboulema** [comment]
Awesome!

Release has been done on the Market place :)

**Comment by noam-honig** [comment]
Cool - updated the article to reference it:
http://doc.fireflymigration.com/stack-trace-explorer.html

Thanks again
