### ISSUE TITLE
Feature request - Adding Paste, and Paste in new tab to the tool box

### ISSUE THREAD

**Issue by noam-honig** [sboulema/StackTraceExplorer#8]
Currently the toolbox has a definition of word wrap.

I'll be great if there will be two more buttons, Paste call stack to this tab, Paste call stack to new tab.

I think it'll make the usage easier.

Thanks

**Comment by sboulema** [comment]
Thanks for the suggestion!

Buttons have been added and will be available in the next release

**Comment by noam-honig** [comment]
Let me know when you make the next release (also to the Visual Studio stack)

I want to create a video for my customer explaining the usage.

I want to replace my existing recommendation page, to one that refers to you.

Here is what I've got now that refers to another tool.
http://doc.fireflymigration.com/stack-trace-explorer.html
